name: CI
on:
  push:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    strategy:
      matrix:
        python: [2.7, pypy2, 3.5, 3.6, 3.7, 3.8, 3.9, pypy3]
    name: Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: |
          python -m pip install --upgrade pip
      - run: pip install .
      - run: ./test/test.sh
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
